/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaskPlannerRouteImport } from './routes/task-planner'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as MeetingSummaryRouteImport } from './routes/meeting-summary'
import { Route as EmailGeneratorRouteImport } from './routes/email-generator'
import { Route as DailyPlannerRouteImport } from './routes/daily-planner'
import { Route as IndexRouteImport } from './routes/index'

const TaskPlannerRoute = TaskPlannerRouteImport.update({
  id: '/task-planner',
  path: '/task-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingSummaryRoute = MeetingSummaryRouteImport.update({
  id: '/meeting-summary',
  path: '/meeting-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailGeneratorRoute = EmailGeneratorRouteImport.update({
  id: '/email-generator',
  path: '/email-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyPlannerRoute = DailyPlannerRouteImport.update({
  id: '/daily-planner',
  path: '/daily-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daily-planner': typeof DailyPlannerRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/meeting-summary': typeof MeetingSummaryRoute
  '/research': typeof ResearchRoute
  '/task-planner': typeof TaskPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily-planner': typeof DailyPlannerRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/meeting-summary': typeof MeetingSummaryRoute
  '/research': typeof ResearchRoute
  '/task-planner': typeof TaskPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daily-planner': typeof DailyPlannerRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/meeting-summary': typeof MeetingSummaryRoute
  '/research': typeof ResearchRoute
  '/task-planner': typeof TaskPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daily-planner'
    | '/email-generator'
    | '/meeting-summary'
    | '/research'
    | '/task-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily-planner'
    | '/email-generator'
    | '/meeting-summary'
    | '/research'
    | '/task-planner'
  id:
    | '__root__'
    | '/'
    | '/daily-planner'
    | '/email-generator'
    | '/meeting-summary'
    | '/research'
    | '/task-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DailyPlannerRoute: typeof DailyPlannerRoute
  EmailGeneratorRoute: typeof EmailGeneratorRoute
  MeetingSummaryRoute: typeof MeetingSummaryRoute
  ResearchRoute: typeof ResearchRoute
  TaskPlannerRoute: typeof TaskPlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/task-planner': {
      id: '/task-planner'
      path: '/task-planner'
      fullPath: '/task-planner'
      preLoaderRoute: typeof TaskPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-summary': {
      id: '/meeting-summary'
      path: '/meeting-summary'
      fullPath: '/meeting-summary'
      preLoaderRoute: typeof MeetingSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-generator': {
      id: '/email-generator'
      path: '/email-generator'
      fullPath: '/email-generator'
      preLoaderRoute: typeof EmailGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-planner': {
      id: '/daily-planner'
      path: '/daily-planner'
      fullPath: '/daily-planner'
      preLoaderRoute: typeof DailyPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DailyPlannerRoute: DailyPlannerRoute,
  EmailGeneratorRoute: EmailGeneratorRoute,
  MeetingSummaryRoute: MeetingSummaryRoute,
  ResearchRoute: ResearchRoute,
  TaskPlannerRoute: TaskPlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
